/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as LoginRouteImport } from './routes/login'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiReferenceRouteImport } from './routes/api.reference'
import { Route as ApiReferenceResourceIdRouteImport } from './routes/api.reference_.$resourceId'

const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceRoute = ApiReferenceRouteImport.update({
  id: '/api/reference',
  path: '/api/reference',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiReferenceResourceIdRoute = ApiReferenceResourceIdRouteImport.update({
  id: '/api/reference_/$resourceId',
  path: '/api/reference/$resourceId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/reference': typeof ApiReferenceRoute
  '/api/reference/$resourceId': typeof ApiReferenceResourceIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/reference': typeof ApiReferenceRoute
  '/api/reference/$resourceId': typeof ApiReferenceResourceIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/register': typeof RegisterRoute
  '/api/reference': typeof ApiReferenceRoute
  '/api/reference_/$resourceId': typeof ApiReferenceResourceIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/register'
    | '/api/reference'
    | '/api/reference/$resourceId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/register'
    | '/api/reference'
    | '/api/reference/$resourceId'
  id:
    | '__root__'
    | '/'
    | '/login'
    | '/register'
    | '/api/reference'
    | '/api/reference_/$resourceId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  LoginRoute: typeof LoginRoute
  RegisterRoute: typeof RegisterRoute
  ApiReferenceRoute: typeof ApiReferenceRoute
  ApiReferenceResourceIdRoute: typeof ApiReferenceResourceIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference': {
      id: '/api/reference'
      path: '/api/reference'
      fullPath: '/api/reference'
      preLoaderRoute: typeof ApiReferenceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/reference_/$resourceId': {
      id: '/api/reference_/$resourceId'
      path: '/api/reference/$resourceId'
      fullPath: '/api/reference/$resourceId'
      preLoaderRoute: typeof ApiReferenceResourceIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  LoginRoute: LoginRoute,
  RegisterRoute: RegisterRoute,
  ApiReferenceRoute: ApiReferenceRoute,
  ApiReferenceResourceIdRoute: ApiReferenceResourceIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
